// <auto-generated />
using CeylanTurizm.Data.Concrete.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CeylanTurizm.Data.Migrations
{
    [DbContext(typeof(CeylanTurizmDbContext))]
    [Migration("20220602150802_mg3")]
    partial class mg3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CeylanTurizm.Entity.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusDriver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusPlaque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusSeatingCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpedition")
                        .HasColumnType("bit");

                    b.HasKey("BusId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityDescription3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityDescription4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityDescription5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityNo")
                        .HasColumnType("int");

                    b.Property<string>("CityTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.Expedition", b =>
                {
                    b.Property<int>("ExpeditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("ExpeditionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpeditionFinish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpeditionHour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExpeditionPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExpeditionStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpeditionStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("bit");

                    b.HasKey("ExpeditionId");

                    b.HasIndex("BusId");

                    b.ToTable("Expeditions");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.TicketSales", b =>
                {
                    b.Property<int>("TicketSalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("customerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerTcNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerTelNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketSalesId");

                    b.HasIndex("ExpeditionId");

                    b.ToTable("TicketSales");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.Expedition", b =>
                {
                    b.HasOne("CeylanTurizm.Entity.Bus", "Bus")
                        .WithMany("Expeditions")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.TicketSales", b =>
                {
                    b.HasOne("CeylanTurizm.Entity.Expedition", "Expedition")
                        .WithMany("TicketSales")
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expedition");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.Bus", b =>
                {
                    b.Navigation("Expeditions");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.Expedition", b =>
                {
                    b.Navigation("TicketSales");
                });
#pragma warning restore 612, 618
        }
    }
}
